### PR TITLE
Add ignoreNotFound command to the uninstall process

### LINKED ISSUE #25: kubernetes mixin should allow uninstall step to succeed when resources are not found
# Synopsis

In the uninstall action the kubernetes mixin should be able to handle situations where resources are not found in a graceful manner.

# Reasoning 

Attempting to recover from a failed bundle installation using uninstall can be almost impossible. If the step creating the k8s resource hasn't been executed the uninstall of said resources will fail hard.

# Proposed solution

Add a boolean `ignore-not-found` property to the uninstall step that adds `--ignore-not-found=<value>`  to the executed command.
That would allow users of the mixin to have uninstall steps that will succeed even if the resource is gone (or have never been there)

### PR DESCRIPTION
**Pull request by MChorfa**
This will allow the user to define `ignoreNotFound` command and avoid the uninstall action of failing if the resource is not present

Close #25

### CODE REVIEW

**Comment by carolynvs** [comment]
Oh sorry I didn't see the original issue because I was on vacation. I would like us to consider not having a mixin configuration for `ignoreNotFound` and instead using this behavior by default during uninstall. So keep part of this PR, but not the mixin config.

One of the design goals of mixins is to not just convert yaml to executable commands but to make the usage of the command robust and fit with how bundles are intended to work. The helm (2) mixin to use this logic for uninstall already, and does not throw an error when one of the requested releases is already gone. That scenario is very common and I think most mixins should handle it if they can. 

Consider an expected scenario with bundles:

1. Install a bundle
2. Try to uninstall a bundle and having something fail partway through after some reasons have been deleted. Perhaps there was a network connectivity problem, a timeout, etc.
3. The user needs to complete the uninstall, and they rerun `porter uninstall`. At that point, it's really important that the mixins don't fail when asked to remove something that was removed already in step 2.

I think that by gracefully handling requests to delete a resource that is already gone would work better with people's expectations for bundles. What do you think?

**Comment by carolynvs** [comment]
@MChorfa I ran into this today and am interested in getting either a version of this PR merged (where it is the default behavior) or a new one. Do you have time to keep working on this one or would you mind if I submitted a PR?

**Comment by MChorfa** [comment]
Hi @carolynvs, I haven't had the time to address the review of this PR. If you have a PR, please go ahead. I might have some time starting next week. Thank you

**Comment by carolynvs** [comment]
Thanks! I'll use your change, but make it the default behavior and make sure you have co-author credit. I really appreciate you getting this started! 🙇‍♀️

**Comment by carolynvs** [comment]
I opened a follow-up PR that builds on this one in #27

**Pull request merged**
